export const products = [
  {
    id: 1,
    name: 'Elegant Watch',
    description: 'A classic timepiece for every occasion.',
    price: '$99.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/FF5733/FFFFFF?text=Elegant+Watch',
  },
  {
    id: 2,
    name: 'Smartphone Holder',
    description: 'Keep your phone secure and visible while driving.',
    price: '$19.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/FFC300/FFFFFF?text=Smartphone+Holder',
  },
  {
    id: 3,
    name: 'Stylish Sunglasses',
    description: 'Protect your eyes with flair.',
    price: '$49.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/C70039/FFFFFF?text=Stylish+Sunglasses',
  },
  {
    id: 4,
    name: 'Wireless Headphones',
    description: 'Enjoy your music without tangled cords.',
    price: '$79.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/900C3F/FFFFFF?text=Wireless+Headphones',
  },
  {
    id: 5,
    name: 'Travel Backpack',
    description: 'Stay organized on the go.',
    price: '$39.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/581845/FFFFFF?text=Travel+Backpack',
  },
  {
    id: 6,
    name: 'Gourmet Coffee Beans',
    description: 'Start your day with the perfect cup.',
    price: '$12.99',
    category: 'Beverages',
    image: 'https://via.placeholder.com/150/003366/FFFFFF?text=Gourmet+Coffee+Beans',
  },
  {
    id: 7,
    name: 'Fitness Tracker',
    description: 'Monitor your health and workouts.',
    price: '$69.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/00A65A/FFFFFF?text=Fitness+Tracker',
  },
  {
    id: 8,
    name: 'Portable Charger',
    description: 'Never run out of battery on the go.',
    price: '$29.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/4CAF50/FFFFFF?text=Portable+Charger',
  },
  {
    id: 9,
    name: 'Cooking Utensil Set',
    description: 'Upgrade your kitchen essentials.',
    price: '$24.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/FFC107/FFFFFF?text=Cooking+Utensil+Set',
  },
  {
    id: 10,
    name: 'Aromatherapy Diffuser',
    description: 'Create a relaxing atmosphere at home.',
    price: '$34.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/8BC34A/FFFFFF?text=Aromatherapy+Diffuser',
  },
  {
    id: 11,
    name: 'Stainless Steel Water Bottle',
    description: 'Stay hydrated in style.',
    price: '$14.99',
    category: 'Beverages',
    image: 'https://via.placeholder.com/150/FF9800/FFFFFF?text=Stainless+Steel+Water+Bottle',
  },
  {
    id: 12,
    name: 'Memory Foam Pillow',
    description: 'Sleep soundly with ergonomic support.',
    price: '$29.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/03A9F4/FFFFFF?text=Memory+Foam+Pillow',
  },
  {
    id: 13,
    name: 'Digital Alarm Clock',
    description: 'Wake up refreshed with gentle sounds.',
    price: '$19.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/FFEB3B/FFFFFF?text=Digital+Alarm+Clock',
  },
  {
    id: 14,
    name: 'Leather Wallet',
    description: 'Organize your essentials with sophistication.',
    price: '$49.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/4CAF50/FFFFFF?text=Leather+Wallet',
  },
  {
    id: 15,
    name: 'Yoga Mat',
    description: 'Find your zen during workouts.',
    price: '$24.99',
    category: 'Fitness',
    image: 'https://via.placeholder.com/150/9C27B0/FFFFFF?text=Yoga+Mat',
  },
  {
    id: 16,
    name: 'Electric Toothbrush',
    description: 'Upgrade your dental hygiene routine.',
    price: '$39.99',
    category: 'Health & Personal Care',
    image: 'https://via.placeholder.com/150/009688/FFFFFF?text=Electric+Toothbrush',
  },
  {
    id: 17,
    name: 'Wireless Mouse',
    description: 'Navigate your computer with ease.',
    price: '$19.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/FF9800/FFFFFF?text=Wireless+Mouse',
  },
  {
    id: 18,
    name: 'Bluetooth Speaker',
    description: 'Enjoy your favorite tunes anywhere.',
    price: '$59.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/FFC107/FFFFFF?text=Bluetooth+Speaker',
  },
  {
    id: 19,
    name: 'Resistance Bands Set',
    description: 'Level up your home workouts.',
    price: '$34.99',
    category: 'Fitness',
    image: 'https://via.placeholder.com/150/03A9F4/FFFFFF?text=Resistance+Bands+Set',
  },
  {
    id: 20,
    name: 'Insulated Lunch Box',
    description: 'Keep your meals fresh on the go.',
    price: '$19.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/4CAF50/FFFFFF?text=Insulated+Lunch+Box',
  },
  {
    id: 21,
    name: 'Travel Neck Pillow',
    description: 'Sleep comfortably during long journeys.',
    price: '$12.99',
    category: 'Travel',
    image: 'https://via.placeholder.com/150/9C27B0/FFFFFF?text=Travel+Neck+Pillow',
  },
  {
    id: 22,
    name: 'Stylish Backpack',
    description: 'Carry your essentials in trendsetting fashion.',
    price: '$49.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/FFEB3B/FFFFFF?text=Stylish+Backpack',
  },
  {
    id: 23,
    name: 'Gaming Mousepad',
    description: 'Enhance your gaming experience.',
    price: '$9.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/009688/FFFFFF?text=Gaming+Mousepad',
  },
  {
    id: 24,
    name: 'Plant-Based Protein Powder',
    description: 'Fuel your workouts with natural ingredients.',
    price: '$29.99',
    category: 'Fitness',
    image: 'https://via.placeholder.com/150/FF5733/FFFFFF?text=Plant-Based+Protein+Powder',
  },
  {
    id: 25,
    name: 'Digital Kitchen Scale',
    description: 'Precisely measure ingredients for perfect recipes.',
    price: '$14.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/03A9F4/FFFFFF?text=Digital+Kitchen+Scale',
  },
  {
    id: 26,
    name: 'Foldable Umbrella',
    description: 'Stay dry in unpredictable weather.',
    price: '$9.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/FF5733/FFFFFF?text=Foldable+Umbrella',
  },
  {
    id: 27,
    name: 'Portable Bluetooth Keyboard',
    description: 'Type comfortably on the go.',
    price: '$39.99',
    category: 'Electronics',
    image: 'https://via.placeholder.com/150/4CAF50/FFFFFF?text=Portable+Bluetooth+Keyboard',
  },
  {
    id: 28,
    name: 'Reusable Shopping Bags',
    description: 'Reduce plastic waste with eco-friendly totes.',
    price: '$9.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/FF9800/FFFFFF?text=Reusable+Shopping+Bags',
  },
  {
    id: 29,
    name: 'Hiking Backpack',
    description: 'Embark on outdoor adventures with confidence.',
    price: '$59.99',
    category: 'Accessories',
    image: 'https://via.placeholder.com/150/03A9F4/FFFFFF?text=Hiking+Backpack',
  },
  {
    id: 30,
    name: 'Handheld Milk Frother',
    description: 'Create barista-quality froth for your beverages.',
    price: '$19.99',
    category: 'Home & Kitchen',
    image: 'https://via.placeholder.com/150/FFC107/FFFFFF?text=Handheld+Milk+Frother',
  },
];

export const categories = [
  { id: 1, label: 'Toolbox', image: 'https://via.placeholder.com/150/FF5733/FFFFFF?text=Toolbox' },
  {
    id: 2,
    label: 'Beverages',
    image: 'https://via.placeholder.com/150/FFC300/FFFFFF?text=Beverages',
  },
  {
    id: 3,
    label: 'Accessories',
    image: 'https://via.placeholder.com/150/C70039/FFFFFF?text=Accessories',
  },
  {
    id: 4,
    label: 'Electronics',
    image: 'https://via.placeholder.com/150/900C3F/FFFFFF?text=Electronics',
  },
  {
    id: 5,
    label: 'Clothing',
    image: 'https://via.placeholder.com/150/581845/FFFFFF?text=Clothing',
  },
  { id: 6, label: 'Books', image: 'https://via.placeholder.com/150/003366/FFFFFF?text=Books' },
  {
    id: 7,
    label: 'Home Decor',
    image: 'https://via.placeholder.com/150/00A65A/FFFFFF?text=Home+Decor',
  },
  { id: 8, label: 'Toys', image: 'https://via.placeholder.com/150/FF5733/FFFFFF?text=Toys' },
  {
    id: 9,
    label: 'Stationery',
    image: 'https://via.placeholder.com/150/FFC300/FFFFFF?text=Stationery',
  },
];
